### ISSUE TITLE
train fail when running seq2seq/finetune_trainer.py ?

### ISSUE THREAD

**Issue by Chriszhangmw** [CristianViorelPopa/BART-TL-topic-label-generation#4]
Hi, I carefully followed your instructions from end_to_end_workflow.ipynb, but when I ran the training process, get the following error, and cannot fix it after debugging, the only difference is that I ran the process on GPU instead of you mentioned TPU, does it influence? hope to hearing from you, thanks.

Traceback (most recent call last):
  File "finetune_trainer.py", line 370, in <module>
    main()
  File "finetune_trainer.py", line 300, in main
    train_result = trainer.train(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/trainer.py", line 756, in train
    self.control = self.callback_handler.on_train_begin(self.args, self.state, self.control)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/trainer_callback.py", line 336, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/trainer_callback.py", line 374, in call_event
    result = getattr(callback, event)(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/integrations.py", line 529, in on_train_begin
    self.setup(args, state, model)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/integrations.py", line 524, in setup
    mlflow.log_params(dict(combined_dict_items[i : i + MLflowCallback.MAX_LOG_SIZE]))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 639, in log_params
    MlflowClient().log_batch(run_id=run_id, metrics=[], params=params_arr, tags=[])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/client.py", line 918, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 292, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics, params=params, tags=tags)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 309, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_internal/azureml_reststore.py", line 72, in _call_endpoint
    return self._call_endpoint_with_retries(super(AzureMLAbstractRestStore, self)._call_endpoint, *args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_internal/azureml_reststore.py", line 61, in _call_endpoint_with_retries
    return execute_func(rest_store_call_endpoint, *args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 68, in execute_func
    return ClientBase._execute_func_internal(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 367, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 433, in _handle_retry
    raise error
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 358, in _execute_func_internal
    response = func(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 185, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'No more than 255 characters per params Value. Request contains 1 of greater length.', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None, 'AdditionalInfo': None}, 'Correlation': {'operation': '985dd51bdaff45870b21d857440c8220', 'request': '621d858b0d0f0c8e'}, 'Environment': 'eastus', 'Location': 'eastus', 'Time': '2022-07-21T08:15:12.9575152+00:00', 'ComponentName': 'mlflow', 'error_code': 'INVALID_PARAMETER_VALUE'}

**Comment by CristianViorelPopa** [comment]
I see that the error log is caused by an error with an MLFlow log. And I found this documentation from the `transformers` library that is also in your logs: https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/callback#transformers.integrations.MLflowCallback. Can you try to disable MLFlow? They say this can be done by setting the environment variable `DISABLE_MLFLOW_INTEGRATION = TRUE`.

**Comment by Chriszhangmw** [comment]
Thanks, it's solved under your hints. actually I do not know where do set this environmental variable, appreciate if you can share.
but after reading the documents from transformer:
MLflowCallback if mlflow is installed.
it means the transformer will call mlflow service if the package is installed, then raise my error, so I just uninstall the package and it works.


by the way, I ran my code on Azure ml

**Comment by CristianViorelPopa** [comment]
I assume, if you have access to the command line on your Azure machine, that you can simply write `export DISABLE_MLFLOW_INTEGRATION=TRUE` and then run things again. But uninstalling also works, was only thinking that you were using MLFlow yourself for experiment tracking. Anyway, glad to know it worked!
